services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: music_streaming
      MYSQL_USER: sa
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql  # Persist database data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

  musicstreaming:
    build: .
    image: musicstreaming:latest
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/music_streaming
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "none"  # Changed to update to help diagnose
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    depends_on:
      mysql:
        condition: service_healthy

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
